name: Update EPF Circulars Search Index

on:
  workflow_dispatch: # Allows manual triggering
  #schedule:
  #  - cron: '0 4 * * 1' # Example: Runs every Monday at 4 AM UTC (after metadata fetch)
  # Alternatively, to run after the metadata fetch workflow completes successfully:
  workflow_run:
    workflows: ["Fetch EPF Circulars Metadata"] # Name of the first workflow
    types:
      - completed
    branches:
      - main # Or your default branch

jobs:
  update_index:
    runs-on: ubuntu-latest
    # Uncomment the following 'if' condition if using workflow_run to ensure it only runs on success
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        # If using workflow_run, you might need to fetch the latest changes
        # with:
        #   ref: ${{ github.event.workflow_run.head_branch }} # Or your default branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Or your preferred Python version

      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Install Python dependencies for indexing
        run: pip install requests beautifulsoup4 pymupdf pytesseract Pillow # All dependencies for --action index

      - name: Run indexing script
        run: python ./fetch.py --action index # Assumes fetch.py is in the root

      - name: Commit and push index-data.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add index-data.json
          if git diff --staged --quiet; then
            echo "No changes to index-data.json."
          else
            git commit -m "Update EPF circulars search index (index-data.json)"
            git push
            echo "index-data.json committed and pushed."
          fi
