name: Update EPF Circulars Feiss Search Index

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 4 * * 1' # Runs every Monday at 4 AM UTC
  # workflow_run: # Alternative trigger if you want to run after another workflow
  #   workflows: ["Fetch EPF Circulars Metadata"]
  #   types:
  #     - completed
  #   branches:
  #     - main # Or your default branch

jobs:
  update_faiss_index_job: # Renamed job for clarity
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }} # Uncomment if using workflow_run

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        # with: # Uncomment if using workflow_run and need specific ref
        #   ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Or your preferred Python version

      - name: Install system dependencies for PDF processing and OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils  # poppler-utils for pdf2image

      - name: Install Python dependencies for FAISS indexing with OCR
        run: |
          pip install --upgrade pip
          # Dependencies for an OCR-based FAISS indexing script:
          pip install \
            requests \
            Pillow \
            pymupdf \
            pdf2image \
            opencv-python \
            easyocr \
            "transformers[torch]" \
            sentence-transformers \
            faiss-cpu \
            torch torchvision torchaudio \
            timm
          # Add any other specific dependencies your update_faiss_index.py script requires.

      - name: Run FAISS indexing script
        env: # Environment variables can be useful for script configuration
          PYTHONIOENCODING: "UTF-8"
        run: |
          # Ensure your update_faiss_index.py script handles batching and state internally,
          # and accepts arguments like --action if you intend to use them.
          # The script should aim to process one batch (e.g., 50 new PDFs) per run.
          python ./update_faiss_index.py # Removed --action index, assuming the script's main purpose is this.
                                         # Add it back if your script uses it: python ./update_faiss_index.py --action index

      - name: Commit and push FAISS index files and status
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          # Add the FAISS index, its metadata, and the indexing status/log file.
          # Adjust file names if your script produces different ones.
          # Using wildcards can be helpful if part of the name is dynamic, but be specific if possible.
          #git add circulars_faiss_ocr.index circulars_faiss_ocr.index.meta.json faiss_indexing_status.json
          git add circulars_faiss_ocr.index circulars_faiss_ocr.index.meta.json processed_pdfs_log.json
          
          if git diff --staged --quiet; then
            echo "No changes to FAISS index files or status."
          else
            # Commit message reflecting FAISS index update
            git commit -m "Update FAISS index and processing status (batch processed)"
            git push
            echo "FAISS index files and/or status committed and pushed."
          fi
